# Generated by Django 2.1.7 on 2019-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190322_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalysis',
            name='desc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='fav_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='follow_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='profile_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='retweet_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='status_count',
            field=models.IntegerField(null=True),
        ),
    ]
