# Generated by Django 2.1.7 on 2019-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190328_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_package',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_package_expires',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='No Address given'),
        ),
    ]
