# Generated by Django 2.1.7 on 2019-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190413_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='party',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
